# 开发者应该设置成自己的wx相关信息
litemall:
  wx:
    app-id: wxcdbe3c9b1a7bb4fe
    app-secret: f48d4c3a9d20e93c4acd2a7f82e1e3ee
    mch-id: 111111
    mch-key: xxxxxx
    notify-url: http://www.example.com/wx/order/pay-notify